jobs:
  deployjob:
    runs-on: self-hosted
    name: Check out and update totem-data files.
    steps:
      - run: |
          ls ${{github.workspace}}
      - name: Checking out the repo.
        uses: actions/checkout@v3.1.0
      - run: |
          ./touch.sh
        working-directory: scripts
      - run: |
          ./update.totem-data.sh
        working-directory: scripts
name: Update and Deploy Totem webapp
on: [push]
